#端口
server:
  port: 8081

  #模板页面
  #注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
#  spring:
#    thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      suffix: .html
#      mode: LEGACYHTML5
#      encoding: UTF-8
#      content-type: text/html
#config:
#    redisAddress: 139.196.96.65
#    port: 6379
##数据源一
#spring:
#      datasource:
#          driverClass: com.mysql.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
#          username: xuan
#          password: 123456
#数据源二
spring:
  data:
    solr:
      host: http://139.196.96.65:8983/solr/
  dubbo:
        application:
          name: springboot-dubbo-demo #应用名
        registry:
          address: zookeeper://139.196.96.65 #zookeeper地址
          port: 2181 #提供注册的端口
        protocol:
          name: dubbo
          port: 20890 #dubbo服务暴露的端口
        scan: com.springboot.dubbo.service.impl #扫描的包名
  redis:
    database: 0
    timeout: 5000
    host: 139.196.96.65
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  datasource:
      name: db
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://139.196.96.65:3306/db01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat
#        cachePrepStmts: true  # 开启二级缓存
#    redis:
#        database:  0
#        host:  127.0.0.1
#        port:  6379
#        password:
#        pool:
#           max-idle: 8
#           min-idle: 0
#           max-active: 8
#           max-wait: -1
#           maxTotal: 8
#           maxWaitMillis: 1000
#        timeout: 60000
#        sentinel:
#             master:
#             nodes:
#spring-boot整合mybatis
mybatis:
  #config-location: classpath:/mapper/config/mybatisConfig.xml #可以注射掉,没用到该配置文件
  mapper-locations: classpath:/mapper/*Mapper.xml

  #type-aliases-package: com.xuan.entity
